FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn -q -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/vote-app.jar /app/vote-app.jar
ENTRYPOINT ["java", "-jar", "/app/vote-app.jar"]

