apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      labels:
        app: result-app
    spec:
      containers:
        - name: result-app
          image: result-app:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: result-frontend
              mountPath: /app/public/index.html
              subPath: index.html
      volumes:
        - name: result-frontend
          configMap:
            name: result-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: result-app-service
spec:
  type: NodePort
  selector:
    app: result-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30081

